# Lint, Test and Build
name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version

      - run: yarn cache dir

      - name: Cache ~/.cache/yarn/v6
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn/v6
          key: npm-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            npm-${{ runner.os }}
            npm-

      - name: Cache ./node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run the tests and generate coverage report
        run: yarn test

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  finish:
    name: Publish coverage data
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
